server.name: kibana
server.host: 0.0.0.0

elasticsearch.hosts: [ http://10.11.0.18:9200, http://10.11.0.19:9200, http://10.11.0.20:9200 ]

monitoring.ui.container.elasticsearch.enabled: true
monitoring.ui.container.logstash.enabled: true
elasticsearch.username: kibana
elasticsearch.password: xxxyyzzzxxx

security.showInsecureClusterWarning: false
